

<!-- 500 words -->
## Conclusions

Pedology and geomorphology are inherently visual, field-based sciences that share a common paradigm and fundamental units of description. Geomorphic description of landforms or geoforms and a merging of these disciplines functionally defined as geopedology is a progression that elevates the geoform as a primary landscape concept that can guide the operational inventory and integrated study of soil geomorphic relationships. Understanding the relevance and importance of contextual linkages to geomorphology in soil survey products adds value and integrates the information with other environmental data and is critical to informing the public and the wider scientific community.  Embracing a visual, quantitative analytical approach to collections of soil profiles and varying formats of soil survey data allows for creative abstraction of geopedologic concepts.

Complex data structures and increasing volumes of available data demand progress in methods that allow iterative aggregation, summary and graphical expression of soil data. The AQP suite of packages works to provide examples and routines that meet these challenges with an emphasis on generalized methods that can be applied to common data structures and designed for analytical efficiency. This collection of tools leverages the flexibility and extensibility of the **R** programming environment. Novel methodologies enable logical checks of data, profile sketches, soil color conversion, slice and slab aggregation, changing of depth support, numerical classification and quantitative synthesis across available soil survey data sources.

 


