---
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    theme: journal
  pdf_document:
    fig_caption: yes
  word_document:
    fig_caption: yes
bibliography: bibliography.bib
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- 800 words, excluding abstract -->
# Introduction

<!-- motivation -->
There has never been a time in the history of soil science where data (soil morphology, physical, chemical, mineralogical, etc.) have been so widely available, and, so closely tied to points on the ground (i.e. GPS coordinates) or high-resolution soil survey databases. However, data alone cannot support decisions or practical advice to land managers. The myriad data sources, formats, and conventions (even within a single institution) further complicate the scientist's or soil surveyor's best efforts to synthesize something useful from a mountain of data. While these problems aren't new (50 hand-written soil profile descriptions would have been difficult to reason over before computers), tools that link database APIs, spatial data, and the inherently complex nature of a soil description are now viable thanks to programming environments like R [@R].

<!-- brief history, foundational work and inspiration -->
The Algorithms for Quantitative Pedology (AQP) project is a suite of packages for the R programming language that simplify most facets of soil data analysis. This project began (2006-2008) as a loosely coordinated (direct email correspondence and the *r-help* mailing list) collection of R scripts used to support the management, analysis, and visualization of digital soil morphology records. By 2010 it became clear that an R package (code, manual pages, and example data following strict guidelines) hosted by CRAN would be the best route forward. The first version of the *aqp* package was submitted to CRAN in May of 2012; with a name and core functionality inspired by the concept of "quantitative pedology" [@Jenny1941Factors], analysis by regular depth-intervals [@harradine1963; Moore1972], and the characterization of depth-functions [@meyers2011]. A companion article by @beaudette2013_AQP contained a detailed description and simple demonstrations of the main package features.


<!-- suite of related packages  -->
Over time, functionality was split into three main categories (i.e. R packages) to increase modularity and divide administrative tasks: *aqp* (soil-specific data structures, profile sketches, color conversion, pedotransfer functions, etc.), *soilDB* (wrapper and convenience functions for accessing APIs and harmonization of results), and *sharpshootR* (specialized tasks and visualizations designed for use with soil database connections provided by *soilDB* and data structures provided by *aqp*). Like most R packages, the AQP suite of packages depends on other packages for optimized computation [@data.table_pkg2021], color conversion  [@farver_pkg2021; @zeileis_colorspace_pkg2020], numerical classification [@cluster_pkg2021], methods for compositional data (e.g. sand, silt, and clay content) [@soiltexture_pkg2018; @compositions_pkg2021] to name a few. The authors hope that other scientists will find a suitable foundation in *aqp*, *soilDB*, and *sharpshootR*, upon which more specialized tools can be built, documented, and delivered in the form of new R packages.


<!-- current use: SoilWeb, NRCS daily business, aqp in the wild -->
Since then ...

[@soilweb2017]

<!-- "Widespread loss of intermediate soil horizons in urban landscapes" [@Herrmann2018] -->






## Example Data

Clarksville pedons and context (Jay)






