
## Water Balance

  * relevance
  * summary concept
  * fetchSCAN(), climate related functions in sharpshootR
  * monthlyWB(), dailyWB(), plotWB()
  * prepareDailyClimateData()
  * AWC inputs and integration with ROSETTA
  
As a state factor in understanding soil formation, climate and the interactions and timing of moisture and temperature, have long held a pivotal role in describing site dynamics at local and regional scales. Thornthwaite developed the first water balance model accounting for inputs of precipitation and losses to evapotranspiration [@thornthwaite]. Water balance metrics relate to soil storage and the downward and upward flux of water through soil and associated soil property development as the soil acts as a sponge responding to atmospheric supply and demand [@arkley1963].  More recently, the correlation of water balance metrics to vegetation growth at sites has become an important tool for the study of site conditions related to existing vegetation distribution and forecasting site climatic trajectories.  High quality and widely accessible gridded climate data has increased the use soil water balance models as a valuable tool for exploring the nuances of climate at a given point on the landscape.   

The `sharpshootR` package provides methods (via dependencies on the `elevatr`, `daymetr`, `Evapotranspiration`, and `hyrdomad` packages) for calculating water balance variables of precipitation (PPT), potential evapotranspiration (PET), actual evapotranspiration (AET), deficit(D), soil moisture storage (S), surplus (U), volumetric water content (VWC) on a monthly `monthlyWB()` and daily `dailyWB()` time steps.  Convenience functions such as `prepareDailyClimateData()` assemble the available water-holding capacity (AWC) values derived for major components in soil map units of the US Soil Survey for specific point coordinates, gridded DAYMET climate data[@daymet] is then downloaded for the specified location and daily water balance metrics are estimated via `dailyWB_SSURGO()`.  

The *soilDB* package provides query access to the station data in the Soil Climate Analysis Network (SCAN).  These stations are instrumented to provide above and below ground climate sensor networks that measure soil temperature, soil moisture, air temperature and precipitation metrics.  Most stations have associated laboratory data in the Kellog Soil Survey Laboratory (KSSL) system.  The data in figure?? is assembled through separate calls to `fetchSCAN()` for the SCAN climate station data and `fetchKSSL()` which gathers the laboratory sampled soil information for the instrumented soil at the SCAN station. 




[@Thornthwaite1948]

[@Arkley_Ulrich1962]
